In [1]:
import threading
import queue
import cProfile
import itertools
import numpy as np

In [4]:
in_queue = queue.Queue()
out_queue = queue.Queue()

def random_number_threading():
    while True:
        n = in_queue.get()
        if n == 'STOP':
            return 
        random_numbers = np.random.rand(n)
        out_queue.put(random_numbers)
        
    if hungry:
        basket.append('sandwich')
    return basket

In [5]:
def generate_random_numbers(show_output, up_to):
    thread = threading.Thread(target=random_number_threading)
    thread.start()
    for i in range(up_to):
        in_queue.put(i)
        random_nums = out_queue.get()
        if show_output:
            print(random_nums)
    in_queue.put('STOP')
    thread.join()

In [6]:
generate_random_numbers(True, 10)

[]
[0.81642519]
[0.90331492 0.18085042]
[0.2227576  0.76768572 0.63800549]
[0.85482783 0.85526127 0.15094082 0.15365999]
[0.9285056  0.50078079 0.12492831 0.79037359 0.79974237]
[0.99724468 0.27022102 0.80176056 0.65988182 0.33803834 0.89548971]
[0.50813754 0.64445287 0.64362642 0.16730836 0.06652572 0.01515624
 0.7651624 ]
[0.86089582 0.82912893 0.52330389 0.17787865 0.30241792 0.12978791
 0.60602561 0.47502916]
[0.22575627 0.89732151 0.89322872 0.5084993  0.88139299 0.55617871
 0.19658182 0.87551189 0.19782614]


In [7]:
cProfile.run('generate_random_numbers(False, 20000)')

         740058 function calls in 2.404 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.036    0.036    2.403    2.403 <ipython-input-5-04f1b90debed>:1(generate_random_numbers)
        1    0.000    0.000    2.404    2.404 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 _weakrefset.py:38(_remove)
        1    0.000    0.000    0.000    0.000 _weakrefset.py:81(add)
    20001    0.041    0.000    0.132    0.000 queue.py:121(put)
    20000    0.063    0.000    2.235    0.000 queue.py:153(get)
    40000    0.012    0.000    0.016    0.000 queue.py:208(_qsize)
    20001    0.007    0.000    0.009    0.000 queue.py:212(_put)
    20000    0.006    0.000    0.008    0.000 queue.py:216(_get)
        1    0.000    0.000    0.000    0.000 threading.py:1012(join)
        1    0.000    0.000    0.000    0.000 threading.py:1050(_wait_for_tstate_lock)
        2    0.000    0.000    0.000    0.000 threadin